### ISSUE TITLE
InjectIntoCriticalProcesses is not set properly by the configuration GUI

### ISSUE THREAD

**Issue by aubymori** [ramensoftware/windhawk#136]
When changing the *Load mods in critical system processes* setting, the registry is not updated fully.

![image](https://github.com/ramensoftware/windhawk/assets/44238627/df0267e0-04ed-4b0f-b441-f9ff8f9ed95f)

I will be showcasing this with the "Shrink Address Bar Height" mod.

Registry after editing GUI:
![image](https://github.com/ramensoftware/windhawk/assets/44238627/f3b82476-73a9-498c-8c95-c978742ab466)

Control Panel with this registry configuration (late inject!):
![image](https://github.com/ramensoftware/windhawk/assets/44238627/a16c854a-a910-4dda-8285-60fa8e0003c9)

Registry after manually updating:
![image](https://github.com/ramensoftware/windhawk/assets/44238627/216bc188-0fad-418d-b407-1a6e0b9fa62f)

Control Panel with this registry configuration (injected just fine!):
![image](https://github.com/ramensoftware/windhawk/assets/44238627/794ec6b1-8735-4319-9c6b-dd13c8e564b1)

**Comment by m417z** [comment]
The _Load mods in critical system processes_ setting only affects `LoadModsInCriticalSystemProcesses` in the registry, that's by design. The `InjectIntoCriticalProcesses` registry value is affected by the _Process exclusion list_ in settings.

### Process exclusion list/Process inclusion list

These settings control which processes will be touched by Windhawk at all. If excluded, Windhawk engine won't be injected into a process, and as a result:
* No mods will be loaded regardless of the other settings or target definitions.
* Windhawk won't be intercepting child processes that this process creates, as described in the settings.

The `InjectIntoCriticalProcesses` registry value is set to `1` when the special `<critical_system_processes>` item is removed from the _Process exclusion list_.

### Load mods in critical system processes

This setting determines when mods are loaded into system processes. By default, system processes are excluded altogether (with `<critical_system_processes>`), so this setting has no effect unless _Process exclusion list_/_Process inclusion list_ are changes.

For example, if there are two mods, `mod-all` targeting `*` and `mod-dwm` targeting `dwm.exe`, then:

* **Never** - both mods won't be loaded in `dwm.exe`.
* **Only if targeted explicitly** - only `mod-dwm` will be loaded in `dwm.exe`.
* **If targeted explicitly or implicitly** - both mods will be loaded in `dwm.exe`.

For your use-case of Control Panel injection (https://github.com/ramensoftware/windhawk/issues/103), you need to make sure `svchost.exe` isn't excluded in the Process exclusion/inclusion lists. You can either remove `<critical_system_processes>` from the exclusion list, or add `svchost.exe` to the inclusion list as following:

![image](https://github.com/ramensoftware/windhawk/assets/4129781/e84c9c2f-9cb4-42f3-b6ee-f469f54b4827)

The _Load mods in critical system processes_ setting can stay at **Only if targeted explicitly**.
