### ISSUE TITLE
Add support for Windows 11 24H2 26100.268

### ISSUE THREAD

**Issue by D3ZOXY** [ramensoftware/windhawk#191]

**Comment by m417z** [comment]
Windhawk supports this, and other Windows 11 preview builds, but not all mods are supported. Here are some relevant issues:
https://github.com/ramensoftware/windhawk-mods/issues/562
https://github.com/ramensoftware/windhawk-mods/issues/611
https://github.com/ramensoftware/windhawk-mods/issues/647

On the other hand, here are examples of mods which I believe work fine on preview builds: Taskbar Volume Control, Slick Window Arrangement, Chrome/Edge scroll tabs with mouse wheel, No Focus Rectangle, Legacy File Copy, and others.

The thing is, some mods are more tailored to specific Windows versions or more likely to become incompatible with Windows updates, especially if the relevant functionality is changed in Windows.

In addition, Microsoft removed some of the debug symbol files which are used by some of the mods for maintenance (see [the relevant blog post](https://ramensoftware.com/windhawk-and-symbol-download-errors)), which means that currently any mods that rely on debug symbols don't work on preview builds.

Since it's not a limitation of Windhawk, but a limitation of each mod, I'm closing this issue.
