### ISSUE TITLE
Windhawk breaks at Windows Update

### ISSUE THREAD

**Issue by T-r-y-o-k-s** [ramensoftware/windhawk#20]
Recently I installed Windhawk, installed a few mods and then did a Windows Update a few days later. After the Update I noticed Windhawk didn't auto start and on launching it manually I experienced the following error message:
```
app\service.cpp(340)\windhawk.exe!009335C1: (caller: 
0092E0EF) Exception(1) tid(1090) 80070424 The specified service 
does not exist as an installed service.
```
When I copied the installation folder to another location, installed Windhawk again and copied the folder back, the mods didn't work (although I made sure their source files were copied), so I had to install them again. But this is propably a different issue.

If it helps, here is a list of the mods I had installed: 
```
Dark Mode for Notepad
Taskbar Clock Customization
Large Taskbar Icons
Text Replace
```

It might be worth mentioning I'm enrolled in the Windows Insider Program for the Windows 11 Dev Channel.
I'll try to reproduce the issue on Windows 11 Release as well as Windows 10.

**Comment by m417z** [comment]
Looks like the service was uninstalled by the update for some reason. In this case, there's not much Windhawk can do about that. Thanks for reporting the issue, I'll keep an eye on it.

Regarding the mods transfer, the program data of Windhawk resides in the `HKEY_LOCAL_MACHINE\SOFTWARE\Windhawk` registry key and in the `C:\ProgramData\Windhawk` folder. I believe that transferring both should work, but it's not something that's officially supported. Since it didn't work for you, my best guess is that you didn't do it quite right.

**Comment by m417z** [comment]
Great, I'm closing the issue.
