### ISSUE TITLE
notifications broke as soon as i installed windhawk and enabled mods

### ISSUE THREAD

**Issue by mefferr** [ramensoftware/windhawk#227]
After installing Windhawk and enabling mods, my Windows 11 notifications stopped working. I can't access the notification center menu at all.

Additionally, the "Notifications settings" page is unresponsive. Essentially, the entire functionality around notifications has completely stopped working.

Here's the error message that's showing up:

![image](https://github.com/user-attachments/assets/ab32e7b4-6348-42d1-a7f1-d321c0ef95d8)

Any suggestions on how to fix this?

**Comment by m417z** [comment]
Does disabling all mods help?

Also, can you capture a crash dump? You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value `2`
* Trigger the error
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by m417z** [comment]
Please upload one of them if you think they're relevant, I'll take a look. You can post a link to Google Drive or a similar service, or [email it to me](https://ramensoftware.com/contact).

**Comment by m417z** [comment]
From the information that's available in the dumps, I see two problems:
* Processes seem to crash when Windhawk is unloaded due to a conflict with another customization tool. I suspect that it might be an incompatibility with MacType.
* Explorer crashes because of the taskbar-labels mod. At this time, 7 other mods are loaded. I suspect it might be caused by windows-11-taskbar-styler and a theme which is incompatible with your settings of taskbar-labels, possibly the running indicator style.

Please check whether disabling MacType fixes it. If not, we'll keep on investigating.

**Comment by m417z** [comment]
Does the problem stop once you exit Windhawk?

**Comment by m417z** [comment]
In this case, as long as you rebooted after uninstalling, it's definitely not Windhawk, since it has no permanent effect on the system. All the modifications are done in memory, no files or registry entries are modified.
