### ISSUE TITLE
SONAR.AM.C!g6

### ISSUE THREAD

**Issue by nybbles2** [ramensoftware/windhawk#254]
Not sure it's a bug, but figured I'd report it....

FYI, Norton is reporting the following all of a sudden:

Filename: windhawk.exe
Threat name: SONAR.AM.C!g6
Full Path: c:\program files\windhawk\windhawk.exe

On computers as of 
4/27/2024 at 5:04:40 PM

Last Used 
8/21/2024 at 9:31:16 PM

Startup Item 
Yes
Launched 
Yes
Behavioral Protection monitors for suspicious program activity on your computer.

Few Users
Hundreds of users in the Norton Community have used this file.

New
This file was released 23 days  ago.

High
This file risk is high.

**Comment by m417z** [comment]
Thanks reporting. It’s likely a false positive detection. Unfortunately, struggling with false positives is a non-ending hassle.

This problem was discussed many times in the blog comments regarding my tools, for example:  
[https://ramensoftware.com/7-taskbar-tweaker/comment-page-43\#comment-11035](https://ramensoftware.com/7-taskbar-tweaker/comment-page-43#comment-11035)  
[https://ramensoftware.com/contact/comment-page-4\#comment-10292](https://ramensoftware.com/contact/comment-page-4#comment-10292)

See also Nir Sofer's blog post, [Antivirus companies cause a big headache to small developers](https://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/), a good write-up about the problem.

You can always help by reporting the detection as a false positive to the relevant antivirus companies. Meanwhile, you might want to add the Windhawk folder/executable to the antivirus exclusion list.

There's not much Windhawk can do about it, so I'm closing this issue.
