### ISSUE TITLE
Start minimized, small pop-up for mods loaded info. Prioritize launch 

### ISSUE THREAD

**Issue by ali-ee** [ramensoftware/windhawk#308]
Hello,

Love this and the mods. Thanks for your efforts so far.

I thought these would be some nice QoL additions to Windhawk. 

- Start minimized option, 
- Small pop-up to relay information like: "mods loaded", "update available" etc.
- Prioritize launch during start-up

Thanks.
Ali

**Comment by m417z** [comment]
Hi, thanks for the feedback.

> * Start minimized option,

I assume that you're using the portable version? See this discussion: https://github.com/ramensoftware/windhawk/discussions/5.

> * Small pop-up to relay information like: "mods loaded", "update available" etc.

You have the "Loaded mods" dialog that can be opened from the tray icon menu. It shows loaded mods, but doesn't have information about available updates.

> Prioritize launch during start-up

Since you're using the portable version, it depends on how you configured it to launch at startup. For a better experience, use the non-portable version that uses a service to launch earlier.
