### ISSUE TITLE
Windhawk Issues after W11 2H24

### ISSUE THREAD

**Issue by jw-mn** [ramensoftware/windhawk#344]
Windhawk was working fine before the W11 2H24 update.  Now, Winhawk settings appear to still be applied for all of the modules but making changes or exiting Windhawk makes no difference in the appearance.  Can't adjust anything.  Ideas?

**Comment by m417z** [comment]
No ideas, but I'm using Win11 24H2 myself, and I know that many other users do, and no similar issues were reported so far. I assume your issue is related to something other than the Windows 11 version.

Have you tried reinstalling Windhawk? If that doesn't help, then perhaps you did something unusual, such as running multiple instances of Windhawk at the same time, which is unsupported. Another possible reason I can think of is an antivirus interfering with Windhawk. If it's none of that, then I'm afraid I'm out of ideas, and I need some more info to be able to help.

**Comment by jw-mn** [comment]
I uninstalled completely and started over and things are working again.  Not sure what happened.  Appreciate the response and I'll mark it closed.
