### ISSUE TITLE
Cannot install on Windows 11 24H2 (Service Start Failed)

### ISSUE THREAD

**Issue by RedDragonTix** [ramensoftware/windhawk#361]
I read to troubleshooting guide, there's nothing about this issue

Everytime I try to install Windhawk, I get this:
![image](https://github.com/user-attachments/assets/ff5e7e93-4d3d-4799-93e0-3313be1fce30)

anyone knows why?

**Comment by RedDragonTix** [comment]
Solved: restarting the computer worked!

**Comment by volute91** [comment]
I have exactly the same problem, and restarting the computer did not change anything. After clicking the OK button, the installer does not proceed further, and I have to click the Cancel button. Although Windhawk can be executed from the Program files and mods can be installed, they do not have any effect whatsoever. I guess that's because the service cannot be started.
I am using a Snapdragon X (ARM64 processor) computer. Could that be the cause of the problem?

**Comment by m417z** [comment]
@volute91 ARM64 devices aren't supported at this time, see https://github.com/ramensoftware/windhawk/issues/11.
