### ISSUE TITLE
windhawk.exe -restart -tray-only

### ISSUE THREAD

**Issue by Aphexus** [ramensoftware/windhawk#84]
When I run this in my startup script it pops up a dialog forcing me to restart explorer.exe due to some mods I'm using. I've looked for a setting to prevent the dialog but I can't find anything. I don't even see an option to start winhawk with windows. Anyways, how can have it automatically restart explorer.exe?

**Comment by m417z** [comment]
> When I run this in my startup script it pops up a dialog forcing me to restart explorer.exe due to some mods I'm using

That's most likely the "Windows 11 Taskbar Styler" mod. It should also say this in the message box title. The message shows up because the taskbar already exists when the mod loads, so restarting explorer is needed to apply the configured styles. Currently, there's no way to turn it off, but you can fork the mod and disable it (change `PromptForExplorerRestart();` lines with `//PromptForExplorerRestart();`).

> I don't even see an option to start winhawk with windows

The standard version should start automatically. Perhaps you're using the portable version. Any reason for that?

**Comment by m417z** [comment]
Fixed in https://github.com/ramensoftware/windhawk-mods/issues/241.
